### ISSUE TITLE
Theme causes cursor to be misaligned

### ISSUE THREAD

**Issue by tarensanders** [johnnybarrels/rstudio-one-dark-pro-theme#2]
Hi @johnnybarrels,

Huge fan of this theme - it's easily my favourite of the ones I've tried. I've been having an issue on both my PC (RStudio 1.4.1048) and Mac (not sure of version) and I'm wondering if you've had the same.

The issue is that the cursor does not align correctly. In the first screenshot, note that the cursor appears in between some brackets, but this is actually the end of the line.

![Screenshot 2021-05-11 142145](https://user-images.githubusercontent.com/20055916/117757943-5a83e880-b264-11eb-8b95-7b7a91e52e88.png)

Switching to a default theme removes this. You can see in the box on the bottom right that the cursor is in the same position (73rd line, 72nd character)

![Screenshot 2021-05-11 142230](https://user-images.githubusercontent.com/20055916/117757937-5952bb80-b264-11eb-8df2-408dffeda128.png)

I've tried changing fonts, font sizes, using sky instead of modern for the RStudio theme. Any other suggestions?

**Comment by johnnybarrels** [comment]
Apologies, I don't know how this issue fell through the cracks.

No I don't have this issue on any of my 3 Mac or Windows machines sorry! Not sure what could be the cause :(

**Comment by tarensanders** [comment]
All good. It's so odd because it shows up on both my Mac and my PC. Must have to do with something else I have installed. If I ever work it out, I'll update the issue.

**Comment by johnnybarrels** [comment]
Thanks heaps. Please do keep me updated if you get to the bottom of it!
